{% set base_name = "libignition-tools" %}
{% set version = "1.5.0" %}
{% set name = base_name + version.split('.')[0] %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ignitionrobotics/ign-tools/archive/ignition-tools_{{ version }}.tar.gz
    sha256: cc99189063b6556e539836a438bdbb9da6eca1fe95a7058d46bfc17debc3d8f5
    patches:
      - fix-backward-install.patch

build:
  number: 3
  skip: true  # [win and ruby==2.6]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - make                               # [not win]
    - ruby
    - ninja                              # [win]
    - cmake
    - pkg-config
  host:
    - backward-cpp
  run:
    - ruby

test:
  commands:
    - test -f ${PREFIX}/lib/cmake/ignition-tools/ignition-tools-config.cmake  # [not win]
    - test -f ${PREFIX}/lib/libignition-tools-backward.so  # [linux]
    - test -f ${PREFIX}/lib/libignition-tools-backward.dylib  # [osx]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\ignition-tools\\ignition-tools-config.cmake (exit 1)  # [win]

about:
  home: https://github.com/ignitionrobotics/ign-tools
  license: Apache-2.0
  license_file: LICENSE
  summary: Ignition Tools

extra:
  recipe-maintainers:
    - seanyen
    - wolfv
    - traversaro
    - j-rivero
